import React, { useState, useEffect } from 'react';
import { ArrowLeftIcon, PlusIcon, StarIcon, ChartBarIcon, UserGroupIcon, TrophyIcon, SearchIcon, FilterIcon } from './icons'; // Assume these icons exist or reuse similar
import type { Page, Employee, Evaluation, Achievement, User } from '../types';
import { fetchTable, insertItem, updateItem } from '../services/supabaseService';
import MSMLogo from './MSMLogo'; // Reuse logo if needed

interface PeopleManagementProps {
    setPage: (page: Page) => void;
    currentUser: User | null;
}

const StarRating: React.FC<{ score: number; onChange?: (score: number) => void; max?: number; readonly?: boolean }> = ({ score, onChange, max = 5, readonly = false }) => {
    return (
        <div className="flex space-x-1">
            {Array.from({ length: max }).map((_, i) => (
                <button
                    key={i}
                    type="button"
                    onClick={() => !readonly && onChange && onChange(i + 1)}
                    className={`${readonly ? 'cursor-default' : 'cursor-pointer hover:scale-110 transition-transform'}`}
                    disabled={readonly}
                >
                    <StarIcon
                        className={`h-6 w-6 ${i < score ? 'text-yellow-400 fill-current' : 'text-gray-300'}`}
                    />
                </button>
            ))}
        </div>
    );
};

const EmployeeCard: React.FC<{ employee: Employee; onSelect: () => void; evaluations: Evaluation[] }> = ({ employee, onSelect, evaluations }) => {
    // Determine average score from last 5 evaluations? Or all? Let's take global average for simplicity or last one.
    // The prompt says "Pontuação / evolução". Let's show the latest score or average.

    // Sort evaluations by date desc
    const employeeEvals = evaluations.filter(e => e.employeeId === employee.id).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

    const lastEvaluation = employeeEvals[0];
    const averageScore = lastEvaluation ? lastEvaluation.totalScore / 5 : 0; // Average per category (max 5) or total score? 
    // Total score is sum of 5 categories (max 25).
    // Let's display stars (0-5). So Total / 5 categories.

    const displayScore = lastEvaluation ? (lastEvaluation.totalScore / 5) : 0;

    return (
        <div onClick={onSelect} className="bg-white rounded-xl shadow-sm hover:shadow-md transition-all cursor-pointer border border-slate-100 p-4 flex items-center space-x-4">
            <div className="h-16 w-16 rounded-full bg-slate-200 flex items-center justify-center overflow-hidden border-2 border-slate-100">
                {employee.photoUrl ? (
                    <img src={employee.photoUrl} alt={employee.name} className="h-full w-full object-cover" />
                ) : (
                    <span className="text-2xl font-bold text-slate-400">{employee.name.charAt(0)}</span>
                )}
            </div>
            <div className="flex-grow">
                <h3 className="font-bold text-slate-800">{employee.name}</h3>
                <p className="text-sm text-slate-500">{employee.sector} • {employee.shift}</p>
                <div className="flex items-center mt-1">
                    <StarIcon className="h-4 w-4 text-yellow-400 fill-current mr-1" />
                    <span className="font-bold text-slate-700">{displayScore.toFixed(1)}</span>
                    <span className="text-xs text-slate-400 ml-2">({employeeEvals.length} avaliações)</span>
                </div>
            </div>
            <div className="text-blue-500">
                <ChartBarIcon className="h-6 w-6" />
            </div>
        </div>
    );
};

const EvaluationModal: React.FC<{ employee: Employee; onClose: () => void; onSave: () => void; currentUser: User | null }> = ({ employee, onClose, onSave, currentUser }) => {
    const [scores, setScores] = useState({
        organization: 0,
        cleanliness: 0,
        effort: 0,
        communication: 0,
        improvement: 0
    });
    const [note, setNote] = useState('');

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!currentUser) return;

        try {
            await insertItem<Evaluation>('evaluations', {
                // @ts-ignore - id will be generated by service
                employeeId: employee.id,
                evaluator: currentUser.username,
                date: new Date().toISOString(),
                organizationScore: scores.organization,
                cleanlinessScore: scores.cleanliness,
                effortScore: scores.effort,
                communicationScore: scores.communication,
                improvementScore: scores.improvement,
                note: note
            } as Evaluation);
            alert('Avaliação registrada com sucesso!');
            onSave();
            onClose();
        } catch (error) {
            console.error(error);
            alert('Erro ao salvar avaliação.');
        }
    };

    const categories = [
        { key: 'organization', label: 'Organização', desc: 'Área limpa, ferramentas no lugar' },
        { key: 'cleanliness', label: 'Limpeza Máquina', desc: 'Máquina limpa, sem óleo excessivo' },
        { key: 'effort', label: 'Empenho', desc: 'Cumpre rotina, proatividade' },
        { key: 'communication', label: 'Comunicação', desc: 'Reporta problemas, troca de turno' },
        { key: 'improvement', label: 'Melhoria', desc: 'Sugestões, participação' },
    ];

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col max-h-[90vh]">
                <div className="bg-slate-50 p-6 border-b border-slate-100 flex justify-between items-center">
                    <div>
                        <h2 className="text-xl font-bold text-slate-800">Avaliar {employee.name}</h2>
                        <p className="text-sm text-slate-500">Avaliação rápida de desempenho</p>
                    </div>
                    <button onClick={onClose} className="text-slate-400 hover:text-slate-600">✕</button>
                </div>

                <form onSubmit={handleSubmit} className="p-6 overflow-y-auto space-y-6">
                    {categories.map((cat) => (
                        <div key={cat.key} className="bg-slate-50 p-4 rounded-xl">
                            <div className="flex justify-between items-center mb-2">
                                <label className="font-bold text-slate-700">{cat.label}</label>
                                {/* @ts-ignore */}
                                <StarRating score={scores[cat.key]} onChange={(v) => setScores({ ...scores, [cat.key]: v })} />
                            </div>
                            <p className="text-xs text-slate-500">{cat.desc}</p>
                        </div>
                    ))}

                    <div>
                        <label className="block text-sm font-medium text-slate-700 mb-2">Observação (Opcional)</label>
                        <textarea
                            value={note}
                            onChange={e => setNote(e.target.value)}
                            className="w-full border border-slate-300 rounded-lg p-3 text-sm focus:ring-2 focus:ring-blue-500 outline-none"
                            placeholder="Algum comentário extra?"
                            rows={3}
                        />
                    </div>

                    <button type="submit" className="w-full bg-[#0F3F5C] text-white font-bold py-3 rounded-xl hover:bg-[#0A2A3D] transition shadow-lg transform hover:-translate-y-1">
                        Confirmar Avaliação
                    </button>
                </form>
            </div>
        </div>
    );
};

const PeopleManagement: React.FC<PeopleManagementProps> = ({ setPage, currentUser }) => {
    const [employees, setEmployees] = useState<Employee[]>([]);
    const [evaluations, setEvaluations] = useState<Evaluation[]>([]);
    const [achievements, setAchievements] = useState<Achievement[]>([]);
    const [selectedEmployee, setSelectedEmployee] = useState<Employee | null>(null);
    const [isAddModalOpen, setIsAddModalOpen] = useState(false);

    // Employee Form State
    const [newEmployeeName, setNewEmployeeName] = useState('');
    const [newEmployeeSector, setNewEmployeeSector] = useState('');
    const [newEmployeeShift, setNewEmployeeShift] = useState('');

    const loadData = async () => {
        const emp = await fetchTable<Employee>('employees');
        const evals = await fetchTable<Evaluation>('evaluations');
        const achs = await fetchTable<Achievement>('achievements');
        setEmployees(emp);
        setEvaluations(evals);
        setAchievements(achs);
    };

    useEffect(() => {
        loadData();
    }, []);

    const handleAddEmployee = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            await insertItem<Employee>('employees', {
                // @ts-ignore
                name: newEmployeeName,
                sector: newEmployeeSector,
                shift: newEmployeeShift,
                active: true
            } as Employee);
            alert('Funcionário cadastrado!');
            setIsAddModalOpen(false);
            setNewEmployeeName('');
            setNewEmployeeSector('');
            setNewEmployeeShift('');
            loadData();
        } catch (error) {
            alert('Erro ao cadastrar.');
        }
    };

    return (
        <div className="min-h-screen bg-slate-50 p-4 sm:p-6 md:p-8">
            {selectedEmployee && (
                <EvaluationModal
                    employee={selectedEmployee}
                    currentUser={currentUser}
                    onClose={() => setSelectedEmployee(null)}
                    onSave={loadData}
                />
            )}

            {isAddModalOpen && (
                <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
                    <form onSubmit={handleAddEmployee} className="bg-white p-6 rounded-xl shadow-xl w-full max-w-md">
                        <h2 className="text-xl font-bold mb-4">Novo Funcionário</h2>
                        <input className="w-full p-2 border rounded mb-3" placeholder="Nome" value={newEmployeeName} onChange={e => setNewEmployeeName(e.target.value)} required />
                        <input className="w-full p-2 border rounded mb-3" placeholder="Setor/Máquina" value={newEmployeeSector} onChange={e => setNewEmployeeSector(e.target.value)} required />
                        <select className="w-full p-2 border rounded mb-4" value={newEmployeeShift} onChange={e => setNewEmployeeShift(e.target.value)} required>
                            <option value="">Selecione Turno</option>
                            <option value="Manhã">Manhã</option>
                            <option value="Tarde">Tarde</option>
                            <option value="Noite">Noite</option>
                        </select>
                        <div className="flex justify-end gap-2">
                            <button type="button" onClick={() => setIsAddModalOpen(false)} className="px-4 py-2 bg-slate-200 rounded">Cancelar</button>
                            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded">Salvar</button>
                        </div>
                    </form>
                </div>
            )}

            <header className="flex items-center justify-between mb-8">
                <div className="flex items-center">
                    <button onClick={() => setPage('menu')} className="mr-4 p-2 rounded-full hover:bg-slate-200 transition">
                        <ArrowLeftIcon className="h-6 w-6 text-slate-700" />
                    </button>
                    <div>
                        <h1 className="text-3xl font-bold text-slate-800">Gestão de Pessoas</h1>
                        <p className="text-slate-500">Engajamento, Disciplina e Melhoria Contínua</p>
                    </div>
                </div>
                <button onClick={() => setIsAddModalOpen(true)} className="bg-[#0F3F5C] text-white px-4 py-2 rounded-lg font-bold hover:bg-[#0A2A3D] transition flex items-center gap-2">
                    <PlusIcon className="h-5 w-5" />
                    Novo Funcionário
                </button>
            </header>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {employees.map(emp => (
                    <EmployeeCard
                        key={emp.id}
                        employee={emp}
                        evaluations={evaluations}
                        onSelect={() => setSelectedEmployee(emp)}
                    />
                ))}
                {employees.length === 0 && (
                    <div className="col-span-full text-center py-10 text-slate-500">
                        Nenhum funcionário cadastrado. Adicione o primeiro!
                    </div>
                )}
            </div>
        </div>
    );
};

export default PeopleManagement;
